/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProgressWindow.java
 *
 * Created on May 31, 2010, 9:23:47 PM
 */

package meguiexwindow;

/**
 *
 * @author Andrew
 */
public class ProgressWindow extends javax.swing.JFrame {

    /** Creates new form ProgressWindow */
    public ProgressWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        innerPanel = new javax.swing.JPanel();
        hydrateText = new javax.swing.JLabel();
        avisynthText = new javax.swing.JLabel();
        createJobsText = new javax.swing.JLabel();
        outputJobXMLText = new javax.swing.JLabel();
        editJobXMLText = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        innerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        hydrateText.setForeground(new java.awt.Color(153, 153, 153));
        hydrateText.setText("Hydrating Media Files");

        avisynthText.setForeground(new java.awt.Color(153, 153, 153));
        avisynthText.setText("Generate AviSynth Scripts");

        createJobsText.setForeground(new java.awt.Color(153, 153, 153));
        createJobsText.setText("Create MeGUI Jobs");

        outputJobXMLText.setForeground(new java.awt.Color(153, 153, 153));
        outputJobXMLText.setText("Output Job XML Files");

        editJobXMLText.setForeground(new java.awt.Color(153, 153, 153));
        editJobXMLText.setText("Edit Job XML File");

        javax.swing.GroupLayout innerPanelLayout = new javax.swing.GroupLayout(innerPanel);
        innerPanel.setLayout(innerPanelLayout);
        innerPanelLayout.setHorizontalGroup(
            innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editJobXMLText)
                    .addComponent(outputJobXMLText)
                    .addComponent(createJobsText)
                    .addComponent(avisynthText)
                    .addComponent(hydrateText))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        innerPanelLayout.setVerticalGroup(
            innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hydrateText)
                .addGap(18, 18, 18)
                .addComponent(avisynthText)
                .addGap(18, 18, 18)
                .addComponent(createJobsText)
                .addGap(18, 18, 18)
                .addComponent(outputJobXMLText)
                .addGap(18, 18, 18)
                .addComponent(editJobXMLText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        closeButton.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(innerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(innerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgressWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisynthText;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel createJobsText;
    private javax.swing.JLabel editJobXMLText;
    private javax.swing.JLabel hydrateText;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JLabel outputJobXMLText;
    // End of variables declaration//GEN-END:variables

}
